version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "get-presigned-url"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1angxchzuq7t0"
s3_prefix = "get-presigned-url"
region = "ap-northeast-2"
profile = "thumbsu"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CognitoUserPoolDomainParameter=\"presigned-user\""
image_repositories = []
