AWSTemplateFormatVersion: 2010-09-09
Description: >-
  get-presigned-url

Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        UploadBucket: !Ref S3UploadBucket

Parameters:
  CognitoUserPoolDomainParameter:
    Type: String
    Default: upload-user-pool
    Description: CognitoUserPool Domain Name

Resources:
  # Cognito User Pool
  MyCognitoUserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: MyUserPool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false

  MyCognitoUserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      UserPoolId: !Ref MyCognitoUserPool
      ClientName: "MyUserPoolClient"
      GenerateSecret: false
      CallbackURLs:
        - https://example.com/callback
        - http://localhost:3000/callback
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile
        - get-signed-url-api/read_signed_url
      SupportedIdentityProviders:
        - COGNITO
    DependsOn: MyCognitoUserPoolResourceServer

  MyCognitoUserPoolResourceServer:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties:
      UserPoolId: !Ref MyCognitoUserPool
      Identifier: "get-signed-url-api"
      Name: "Get Signed Url API"
      Scopes:
        - ScopeName: "read_signed_url"
          ScopeDescription: "Read Signed Url"

  MyCognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref MyCognitoUserPool
      Domain:
        Ref: CognitoUserPoolDomainParameter

  PresignedUploadUrlApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'POST, GET, PUT, OPTIONS'"
        AllowHeaders: "'*'"
        AllowOrigin: "'http://localhost:3000'"
        MaxAge: "'600'"
        AllowCredentials: true
      Auth:
        DefaultAuthorizer: MyCognitoAuthorizer
        Authorizers:
          MyCognitoAuthorizer:
            AuthorizationScopes:
              - get-signed-url-api/read_signed_url
            UserPoolArn: !GetAtt MyCognitoUserPool.Arn
        AddDefaultAuthorizerToCorsPreflight: false

  UploadRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/getPreSignedUrl.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        S3WritePolicy:
          BucketName: !Ref S3UploadBucket
      Events:
        UploadAssetApi:
          Type: Api
          Properties:
            RestApiId: !Ref PresignedUploadUrlApi
            Path: /uploads
            Method: GET

  S3UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - POST
              - PUT
            AllowedOrigins:
              - "http://localhost:3000"
            Id: presignedUrlRule
            MaxAge: 3600

Outputs:
  GetSignedUrlServiceApi:
    Description: "API Gateway endpoint URL for prod stage for GetSignedUrlService function"
    Value: !Sub "https://${PresignedUploadUrlApi}.execute-api.${AWS::Region}.amazonaws.com/prod/uploads"
  GetSignedUrlServiceFunction:
    Description: "TodoService Lambda Function ARN"
    Value: !GetAtt UploadRequestFunction.Arn
  GetSignedUrlServiceFunctionIamRole:
    Description: "Implicit IAM Role"
    Value: !GetAtt UploadRequestFunctionRole.Arn
  MyCognitoUserPoolURL:
    Description: "MyCognitoUserPool URL"
    Value: !Sub "https://${CognitoUserPoolDomainParameter}.auth.${AWS::Region}.amazoncognito.com"
  MyCognitoUserPoolClientID:
    Description: "MyCognitoUserPoolClient client_id"
    Value: !Ref MyCognitoUserPoolClient
  S3UploadBucketName:
    Description: "S3 bucket for application uploads"
    Value: !Ref S3UploadBucket
